import 'package:flutter/material.dart';

Color colorHeader = const Color.fromRGBO(183, 129, 79, 1);
Color bgColor = Colors.white;
DateTime? selecteddate;
var valueFeeling = 2;
TextEditingController goal1Field = TextEditingController();
TextEditingController goal2Field = TextEditingController();
TextEditingController goal3Field = TextEditingController();
TextEditingController pleasure1 = TextEditingController();
TextEditingController pleasure2 = TextEditingController();
TextEditingController pleasure3 = TextEditingController();
TextEditingController gratitude1 = TextEditingController();
TextEditingController gratitude2 = TextEditingController();
TextEditingController gratitude3 = TextEditingController();
TextEditingController program1 = TextEditingController();
TextEditingController program2 = TextEditingController();
TextEditingController program3 = TextEditingController();
TextEditingController morningRitual = TextEditingController();
TextEditingController eveRitual = TextEditingController();
TextEditingController priorityController = TextEditingController();
TextEditingController success1 = TextEditingController();
TextEditingController success2 = TextEditingController();
TextEditingController success3 = TextEditingController();
TextEditingController howwasmyday = TextEditingController();
TextEditingController whatwouldido = TextEditingController();
TextEditingController personalNumber = TextEditingController();
TextEditingController businessNumber = TextEditingController();
TextEditingController habitController = TextEditingController();
var goal1, goal2, goal3, pleas1, pleas2, pleas3, habit;
